"""add_gender_avatar_banner_preset

Revision ID: 4cf54c834428
Revises: 689ee21e9bf3
Create Date: 2026-03-27 10:33:31.112025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf54c834428'
down_revision: Union[str, None] = '689ee21e9bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('avatar_preset', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('banner_preset', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_preset')
    op.drop_column('users', 'avatar_preset')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
