"""add_deactivation_fields

Revision ID: 689ee21e9bf3
Revises: 95907afa0cfa
Create Date: 2026-03-27 09:55:55.506733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689ee21e9bf3'
down_revision: Union[str, None] = '95907afa0cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_playlists_search', table_name='playlists', postgresql_using='gin')
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('delete_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deletion_type', sa.String(length=50), nullable=True))
    op.drop_index('idx_users_search', table_name='users', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_search', 'users', [sa.text("to_tsvector('simple'::regconfig, (COALESCE(username, ''::character varying)::text || ' '::text) || COALESCE(display_name, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.drop_column('users', 'deletion_type')
    op.drop_column('users', 'delete_at')
    op.drop_column('users', 'deactivated_at')
    op.create_index('idx_playlists_search', 'playlists', [sa.text("to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
